---
- name: Install Node.js 16 on Amazon Linux 2
  hosts: web
  become: yes

  tasks:
    - name: Ensure curl is installed
      yum:
        name: curl
        state: present

    - name: Add Node.js 16.x repository
      shell: curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js 16
      yum:
        name: nodejs
        state: present

    - name: Check Node.js version
      command: node -v
      register: node_version

    - name: Display installed Node.js version
      debug:
        msg: "Installed Node.js version is {{ node_version.stdout }}"
