---
- name: Install Node.js 16 via NVM on Amazon Linux 2
  hosts: web
  become: true
  become_user: ec2-user

  tasks:
    - name: Install dependencies
      yum:
        name:
          - gcc-c++
          - make
          - curl
        state: present

    - name: Download and install NVM
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        executable: /bin/bash

    - name: Add NVM to bash profile
      lineinfile:
        path: /home/ec2-user/.bashrc
        line: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

    - name: Load NVM and install Node.js 16
      shell: |
        source /home/ec2-user/.bashrc
        . ~/.nvm/nvm.sh
        nvm install 16
        nvm alias default 16
      args:
        executable: /bin/bash

    - name: Check Node.js version
      shell: |
        source /home/ec2-user/.bashrc
        . ~/.nvm/nvm.sh
        node -v
      register: node_version
      args:
        executable: /bin/bash

    - name: Display installed Node.js version
      debug:
        msg: "Installed Node.js version is {{ node_version.stdout }}"