- name: Install Node.js 16 on Amazon Linux 2
  hosts: webservers
  become: yes

  tasks:
    - name: Add Node.js 16.x repository
      shell: curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js 16
      yum:
        name: nodejs
        state: present

    - name: Verify Node.js version
      command: node -v
      register: node_version

    - name: Print Node.js version
      debug:
        var: node_version.stdout