---
- name: Deploy Node.js App on EC2
  hosts: web
  become: true
  vars:
    app_repo: "https://github.com/nenavathsrinu/dev-cicd.git"
    app_dir: "/home/ec2-user/dev-cicd"

  tasks:
    - name: Install dependencies
      yum:
        name:
          - gcc-c++
          - make
          - curl
          - git
        state: present

    - name: Download and install NVM
      become_user: ec2-user
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc
        echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc
        echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' >> ~/.bashrc
        source ~/.bashrc
        . ~/.nvm/nvm.sh
        nvm install 16
        nvm alias default 16
      args:
        executable: /bin/bash

    - name: Clone app repo
      become_user: ec2-user
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Load NVM and install npm dependencies
      become_user: ec2-user
      shell: |
        export NVM_DIR="$HOME/.nvm"
        source ~/.bashrc
        . "$NVM_DIR/nvm.sh"
        cd {{ app_dir }}
        npm install
      args:
        executable: /bin/bash

    - name: Install PM2 globally
      become_user: ec2-user
      shell: |
        export NVM_DIR="$HOME/.nvm"
        source ~/.bashrc
        . "$NVM_DIR/nvm.sh"
        npm install -g pm2
      args:
        executable: /bin/bash

    - name: Start app with PM2
      become_user: ec2-user
      shell: |
        export NVM_DIR="$HOME/.nvm"
        source ~/.bashrc
        . "$NVM_DIR/nvm.sh"
        cd {{ app_dir }}
        pm2 start server.js --name dev-app
        pm2 save
      args:
        executable: /bin/bash

