---
- name: Install Node.js 16 and optionally httpd on Amazon Linux 2
  hosts: all
  become: yes

  vars:
    install_httpd: false  # ✅ Change to true if you want Apache installed

  tasks:

    - name: Add Node.js 16.x repository
      shell: curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Optionally install httpd (Apache)
      yum:
        name: httpd
        state: present
      when: install_httpd

    - name: Start and enable httpd (if installed)
      service:
        name: httpd
        state: started
        enabled: true
      when: install_httpd